package HealthTrackerApp;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

import java.awt.*;
import javax.swing.*;
import java.util.function.Consumer;

public class MailPanel extends javax.swing.JPanel {

    JTextField emailField = new JTextField();
    JTextArea messageArea = new JTextArea(10, 20);
    /**
     * Creates new form MailPanel
     * @param navigator
     */
    public MailPanel(Consumer<String> navigator) {
        initComponents();
        setupComponents(navigator);
    }
    
    private void setupComponents(Consumer<String> navigator) {
        removeAll();
        setLayout(new BorderLayout());
        setBackground(new Color(240, 240, 240));

        // --- NORTH: Title ---
        JLabel title = new JLabel("Mail Summary");
        title.setFont(new Font("SansSerif", Font.BOLD, 16));
        title.setForeground(new Color(180, 50, 50));
        title.setBorder(BorderFactory.createEmptyBorder(20, 20, 10, 0));
        add(title, BorderLayout.NORTH);

        // --- CENTER: Form Fields ---
        JPanel centerPanel = new JPanel();
        centerPanel.setLayout(new BoxLayout(centerPanel, BoxLayout.Y_AXIS));
        centerPanel.setBorder(BorderFactory.createEmptyBorder(10, 20, 10, 20));
        centerPanel.setBackground(new Color(240, 240, 240));

        // Receiver Email Field
        centerPanel.add(new JLabel("To:"));
        emailField = new JTextField();
        emailField.setMaximumSize(new Dimension(Integer.MAX_VALUE, 30));
        centerPanel.add(emailField);

        centerPanel.add(Box.createVerticalStrut(10));

        // Message Text Area
        centerPanel.add(new JLabel("Message:"));
        messageArea = new JTextArea(10, 20);
        messageArea.setLineWrap(true);
        messageArea.setWrapStyleWord(true);
        JScrollPane scrollPane = new JScrollPane(messageArea);
        centerPanel.add(scrollPane);
        add(centerPanel, BorderLayout.CENTER);

        // Message successful label
        JLabel statusLabel = new JLabel(" "); 
        statusLabel.setForeground(new Color(0, 150, 0));
        statusLabel.setAlignmentX(Component.LEFT_ALIGNMENT);
        statusLabel.setPreferredSize(new Dimension(300, 25)); 
        statusLabel.setMinimumSize(new Dimension(300, 25));
        statusLabel.setMaximumSize(new Dimension(300, 25));

        centerPanel.add(statusLabel);
        
        // --- SOUTH: Navigation & Actions ---
        JPanel bottom = new JPanel(new FlowLayout(FlowLayout.RIGHT)); // Switched to Right for "Send" style

        JButton sendButton = new JButton("Send Mail");
        sendButton.addActionListener(e -> {
            emailField.setText("");
            messageArea.setText("");
            statusLabel.setText("✔ Message sent successfully!");
            Timer timer = new Timer(3000, ex -> {statusLabel.setText(" ");});
            timer.setRepeats(false);
            timer.start();
        });

        JButton goToProfile = new JButton("View Profile");
        goToProfile.addActionListener(e -> navigator.accept("tab bars page"));

        bottom.add(goToProfile);
        bottom.add(sendButton);
        add(bottom, BorderLayout.SOUTH);

        revalidate();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
