/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package healthtracker;
import java.awt.*;
import javax.swing.*;
import java.util.function.Consumer;


public class MailPanel extends javax.swing.JPanel {

    private JTextField tfEmail;
    private JTextArea areaMessage;
    private JLabel lblStatus;
    private JButton btnProfile, btnSend;
    private final Consumer<String> navigator;

    
    public MailPanel(Consumer<String> navigator) {
        this.navigator = navigator;
        setupComponents();
    }

    
    private void setupComponents() {
        removeAll();
        setLayout(new BorderLayout());
        setBackground(new Color(240, 240, 240));
        
        buildTitle();
        buildButtons();
        buildTextAreas();
        buildButtonMenu();
        buildCenter();

        revalidate();
        repaint();
    }

    
    private void buildTitle() {
        JLabel title = new JLabel("Mail Summary");
        title.setFont(new Font("SansSerif", Font.BOLD, 16));
        title.setForeground(new Color(180, 50, 50));
        title.setBorder(BorderFactory.createEmptyBorder(20, 20, 10, 0));
        add(title,  BorderLayout.NORTH);
    }

    
    private void buildCenter() {
        JPanel centerPanel = new JPanel();
        centerPanel.setLayout(new BoxLayout(centerPanel, BoxLayout.Y_AXIS));
        centerPanel.setBorder(BorderFactory.createEmptyBorder(10, 20, 10, 20));
        centerPanel.setBackground(new Color(240, 240, 240));

        centerPanel.add(new JLabel("To:"));
        centerPanel.add(tfEmail);
        centerPanel.add(Box.createVerticalStrut(10));
        centerPanel.add(new JLabel("Message:"));
        centerPanel.add(new JScrollPane(areaMessage));
        centerPanel.add(buildStatusLabel());

        add(centerPanel, BorderLayout.CENTER);
    }

    
    private void buildTextAreas() {
        tfEmail = new JTextField();
        tfEmail.setMaximumSize(new Dimension(Integer.MAX_VALUE, 30));
        areaMessage = new JTextArea(10, 20);
        areaMessage.setLineWrap(true);
        areaMessage.setWrapStyleWord(true);
    }

    
    private JLabel buildStatusLabel() {
        lblStatus = new JLabel(" ");
        lblStatus.setForeground(new Color(0, 150, 0));
        lblStatus.setAlignmentX(Component.LEFT_ALIGNMENT);
        lblStatus.setPreferredSize(new Dimension(300, 25));
        lblStatus.setMinimumSize(new Dimension(300, 25));
        lblStatus.setMaximumSize(new Dimension(300, 25));
        return lblStatus;
    }

    
    private void buildButtonMenu() {
        JPanel bottom = new JPanel(new FlowLayout(FlowLayout.RIGHT));
        bottom.add(btnProfile);
        bottom.add(btnSend);
        add(bottom, BorderLayout.SOUTH);
    }
    
    
    public static boolean isValidEmail(String email) {
        int atIndex = email.indexOf("@");
        return email != null && atIndex > 0 &&
               email.charAt(atIndex + 1) != '.' &&  // no dot right after @
               (email.contains(".com") || email.contains(".org") || email.contains(".edu"));
    }
    
    
    private void buildButtons() {
        btnProfile = new JButton("View Profile");
        btnSend = new JButton("Send Mail");
        
        btnProfile.addActionListener(e -> navigator.accept("main"));
        btnSend.addActionListener(e -> sendMail());
    }

    
    private void sendMail() {
        if (!isValidEmail(tfEmail.getText())) {
            lblStatus.setText("Invalid email");
            lblStatus.setForeground(new Color(150, 0, 0));
        }
        else {
            lblStatus.setText("✔ Message sent successfully!");
            lblStatus.setForeground(new Color(0, 150, 0));
        }
        tfEmail.setText("");
        areaMessage.setText("");
        Timer timer = new Timer(3000, e -> lblStatus.setText(" "));
        timer.setRepeats(false);
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>                        


    // Variables declaration - do not modify                     
    // End of variables declaration                   
}
