/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

import java.awt.*;
import javax.swing.*;
import java.util.function.Consumer;

public class MailPanel extends javax.swing.JPanel {

    /**
     * Creates new form MailPanel
     * @param navigator
     */
    public MailPanel(Consumer<String> navigator) {
        initComponents();
        setupComponents(navigator);
    }
    
    private void setupComponents(Consumer<String> navigator) {
        removeAll();
        setLayout(new BorderLayout());
        setBackground(new Color(240, 240, 240));

        JLabel title = new JLabel("Mail Summary");
        title.setFont(new Font("SansSerif", Font.BOLD, 16));
        title.setForeground(new Color(180, 50, 50));
        title.setBorder(BorderFactory.createEmptyBorder(20, 20, 10, 0));
        add(title, BorderLayout.NORTH);

        // Button to go to profile
        JButton goToProfile = new JButton("View Profile");
        goToProfile.addActionListener(e -> navigator.accept("profile"));

        JPanel bottom = new JPanel(new FlowLayout(FlowLayout.LEFT));
        bottom.add(goToProfile);
        add(bottom, BorderLayout.SOUTH);
        revalidate();  // refresh the layout
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
