/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.util.List;
import java.util.ArrayList;
import healthtracker.*;
import java.awt.HeadlessException;
import java.time.LocalDate;
import java.time.LocalTime;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author tamnguyen, Amy Schmieder
 */
public class TabBarsPage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TabBarsPage.class.getName());
    
    /*
    Treatment handling fields
    */
    List<Treatment> treatmentTableContents;
    TreatmentTableModel treatTableModel;
    
    AppointmentDataSource appointmentDataSource;


    /**
     * Creates new form Appointments
     */
    public TabBarsPage() {
        initComponents();
        initTreatments();
        initAppointments();
    }
    
    
    /**
     * populate the jTableTreatments table
     * @author Amy Schmieder
    */
    private void initTreatments() {
        setTreatments(); 
        treatTableModel = new TreatmentTableModel(treatmentTableContents);
        jTableTreatments.setModel(treatTableModel);
        //System.out.println("treatment count = " + jTableTreatments.getRowCount());

    }
       
    /*
    Fill the treatments table. Ideally this would be from a database, but that's 
    for a future time.
    */
    private void setTreatments(){
        treatmentTableContents = Treatment.getData();
//        treatmentTableContents = new ArrayList<Treatment>();
//        treatmentTableContents.add(new Medication(0, 0, "Amoxicillin", "Take with food", "antibiotic", "every 8 hours", "12mg", 20));
//        treatmentTableContents.add(new Treatment(0, 0, "Blood Pressure measurement", "", "Monitor blood pressure", "once a day"));
    }

    /*
    Call the EditTreatment dialog box, handle the results
    */
    private void editSelectedTreatment(int row){
        //System.out.println("Whee! Made it to editTreatment!");
        Treatment origTreatment = treatmentTableContents.get(row);
        
        EditTreatment dialog = new EditTreatment(this, true, origTreatment, false);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        if(dialog.isConfirmed()){
            Treatment updatedTreatment = dialog.getTreatment();
            treatTableModel.updateTreatment(row, updatedTreatment);
        } else if (dialog.isDelete()){
            treatTableModel.deleteTreatment(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        appointmentMain = new javax.swing.JPanel();
        editAppointmentButton = new javax.swing.JButton();
        appointmentSearch = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        deleteAppointmentButton = new javax.swing.JButton();
        newAppointmnetButton = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        appointmentsTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        upcomingAptTextArea = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableTreatments = new javax.swing.JTable();
        jScrollBar2 = new javax.swing.JScrollBar();
        addTreatmentButton = new javax.swing.JButton();
        editTreatmentButton = new javax.swing.JButton();
        delTreatmentButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jLabel5 = new javax.swing.JLabel();
        jScrollBar3 = new javax.swing.JScrollBar();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 30));
        jPanel1.setVerifyInputWhenFocusTarget(false);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("HEALTH REMINDER");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane4.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        jTabbedPane4.setForeground(new java.awt.Color(0, 102, 255));
        jTabbedPane4.setPreferredSize(new java.awt.Dimension(800, 470));

        appointmentMain.setBackground(new java.awt.Color(255, 255, 255));
        appointmentMain.setPreferredSize(new java.awt.Dimension(800, 470));

        editAppointmentButton.setForeground(new java.awt.Color(102, 102, 102));
        editAppointmentButton.setText("Edit Appointment");
        editAppointmentButton.setMaximumSize(new java.awt.Dimension(140, 25));
        editAppointmentButton.addActionListener(this::editAppointmentButtonActionPerformed);

        appointmentSearch.setForeground(new java.awt.Color(102, 102, 102));

        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Search");

        deleteAppointmentButton.setForeground(new java.awt.Color(102, 102, 102));
        deleteAppointmentButton.setText("Delete Appointment");
        deleteAppointmentButton.addActionListener(this::deleteAppointmentButtonActionPerformed);

        newAppointmnetButton.setForeground(new java.awt.Color(102, 102, 102));
        newAppointmnetButton.setText("New Appointment");
        newAppointmnetButton.setMaximumSize(new java.awt.Dimension(140, 25));
        newAppointmnetButton.setPreferredSize(new java.awt.Dimension(140, 25));
        newAppointmnetButton.addActionListener(this::newAppointmnetButtonActionPerformed);

        jScrollPane8.setForeground(new java.awt.Color(102, 102, 102));

        appointmentsTable.setForeground(new java.awt.Color(102, 102, 102));
        appointmentsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Date", "Time", "Doctor", "Address"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        appointmentsTable.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane8.setViewportView(appointmentsTable);

        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Upcoming Appointment");

        upcomingAptTextArea.setEditable(false);
        upcomingAptTextArea.setColumns(20);
        upcomingAptTextArea.setRows(5);
        jScrollPane9.setViewportView(upcomingAptTextArea);

        javax.swing.GroupLayout appointmentMainLayout = new javax.swing.GroupLayout(appointmentMain);
        appointmentMain.setLayout(appointmentMainLayout);
        appointmentMainLayout.setHorizontalGroup(
            appointmentMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(appointmentMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(appointmentMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(appointmentMainLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(newAppointmnetButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(130, 130, 130)
                        .addComponent(editAppointmentButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(130, 130, 130)
                        .addComponent(deleteAppointmentButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, appointmentMainLayout.createSequentialGroup()
                        .addGroup(appointmentMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(appointmentMainLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(appointmentSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3))
                            .addComponent(jScrollPane8))
                        .addGap(16, 16, 16))
                    .addComponent(jScrollPane9)
                    .addGroup(appointmentMainLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        appointmentMainLayout.setVerticalGroup(
            appointmentMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(appointmentMainLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(appointmentMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(appointmentSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                .addGap(16, 16, 16)
                .addGroup(appointmentMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newAppointmnetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editAppointmentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteAppointmentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        jTabbedPane4.addTab("Appointments", appointmentMain);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jTableTreatments.setForeground(new java.awt.Color(102, 102, 102));
        jTableTreatments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableTreatments.setColumnSelectionAllowed(true);
        jTableTreatments.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jTableTreatments.setShowGrid(true);
        jTableTreatments.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableTreatmentsMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableTreatments);
        jTableTreatments.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        addTreatmentButton.setForeground(new java.awt.Color(102, 102, 102));
        addTreatmentButton.setText("New Treatment");
        addTreatmentButton.setMaximumSize(new java.awt.Dimension(140, 25));
        addTreatmentButton.addActionListener(this::addTreatmentButtonActionPerformed);

        editTreatmentButton.setForeground(new java.awt.Color(102, 102, 102));
        editTreatmentButton.setText("Edit Treatment");
        editTreatmentButton.setMaximumSize(new java.awt.Dimension(140, 25));
        editTreatmentButton.addActionListener(this::editTreatmentButtonActionPerformed);

        delTreatmentButton.setForeground(new java.awt.Color(102, 102, 102));
        delTreatmentButton.setText("Delete Treatment");
        delTreatmentButton.setMaximumSize(new java.awt.Dimension(140, 25));
        delTreatmentButton.addActionListener(this::delTreatmentButtonActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(addTreatmentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(136, 136, 136)
                        .addComponent(editTreatmentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 155, Short.MAX_VALUE)
                        .addComponent(delTreatmentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)))
                .addComponent(jScrollBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollBar2, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                        .addGap(64, 64, 64))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addTreatmentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editTreatmentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(delTreatmentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jTabbedPane4.addTab("Treatments", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jTable3.setForeground(new java.awt.Color(102, 102, 102));
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1234", "Jessi", "Dentist", "111-111-1111", "abc@abc.com", "44 Red Dr."},
                {"5666", "Jack", "Ped", "222-222-2222", "adg@adds.com", "356 Hayward"},
                {"333", "Timothy", "Family Doc", "333-333-3333", "tim@daf.com", "123 Vegas Ave., Militas, CA, 95035"},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Speciality", "Phone", "Email", "Address"
            }
        ));
        jTable3.setColumnSelectionAllowed(true);
        jTable3.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane6.setViewportView(jTable3);
        jTable3.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (jTable3.getColumnModel().getColumnCount() > 0) {
            jTable3.getColumnModel().getColumn(0).setResizable(false);
        }

        jScrollPane7.setViewportView(jTextPane2);

        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Search");

        jButton10.setForeground(new java.awt.Color(102, 102, 102));
        jButton10.setText("New Doctor");
        jButton10.setMaximumSize(new java.awt.Dimension(140, 25));
        jButton10.addActionListener(this::jButton10ActionPerformed);

        jButton11.setForeground(new java.awt.Color(102, 102, 102));
        jButton11.setText("Edit Doctor");
        jButton11.setPreferredSize(new java.awt.Dimension(140, 25));
        jButton11.addActionListener(this::jButton11ActionPerformed);

        jButton12.setForeground(new java.awt.Color(102, 102, 102));
        jButton12.setText("Delete Doctor");
        jButton12.setPreferredSize(new java.awt.Dimension(140, 25));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 728, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollBar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollBar3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE))
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("Doctors", jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setForeground(new java.awt.Color(102, 102, 102));

        jButton13.setForeground(new java.awt.Color(102, 102, 102));
        jButton13.setText("Edit Profile");
        jButton13.setMaximumSize(new java.awt.Dimension(140, 25));
        jButton13.addActionListener(this::jButton13ActionPerformed);

        jButton14.setForeground(new java.awt.Color(102, 102, 102));
        jButton14.setText("Delete Profile");
        jButton14.setPreferredSize(new java.awt.Dimension(140, 25));
        jButton14.addActionListener(this::jButton14ActionPerformed);

        jButton15.setForeground(new java.awt.Color(102, 102, 102));
        jButton15.setText("Logout");
        jButton15.setPreferredSize(new java.awt.Dimension(140, 25));

        jScrollPane2.setForeground(new java.awt.Color(102, 102, 102));

        jTextArea2.setColumns(20);
        jTextArea2.setForeground(new java.awt.Color(51, 51, 51));
        jTextArea2.setRows(5);
        jTextArea2.setText("PROFILE INFORMATION:\n\nName: \tAlexa\nDOB:\t12/12/1999\nEmail:\talexa@yahoo.com\nPhone: \t999-999-9999\nAddress:\t333 Halo Ave., Santa Clara, CA, 95077");
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122)
                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                .addGap(16, 16, 16)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        jTabbedPane4.addTab("Profile", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 791, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 791, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    

        
    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed
    
    private void initAppointments(){
        appointmentDataSource = new AppointmentDataSource();
        refreshAptsTable();
        refreshUpcomingAptTextArea();
    }
    
    private void newAppointmnetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newAppointmnetButtonActionPerformed
        AddAppointment add = new AddAppointment(this, appointmentDataSource);
        add.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_newAppointmnetButtonActionPerformed

    void refreshUpcomingAptTextArea(){
        if (appointmentDataSource.isEmpty()){
            upcomingAptTextArea.setText("There is no upcoming appointment.");
        } else
            upcomingAptTextArea.setText(appointmentDataSource.getUpcomingApt().toString());
    }
    
    void refreshAptsTable(){
        DefaultTableModel model = (DefaultTableModel) appointmentsTable.getModel();
        model.setRowCount(0);
        for(Appointment a : appointmentDataSource.getAppointments()){
            model.addRow(new Object[]{
                a.getNiceDateString(),
                a.getTime(),
                a.getDoctor().getName(),
                a.getDoctor().getAddress()
            });
        }
    }
    
    public void refreshPage(){
        this.refreshAptsTable();
        this.refreshUpcomingAptTextArea();
    }
    
    public int getSelectedIndex(){
        return appointmentsTable.getSelectedRow();
    }
    
    private void deleteAppointmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAppointmentButtonActionPerformed

        try {
            int selectedRow = appointmentsTable.getSelectedRow();
            if (selectedRow != -1) {
                int d = JOptionPane.showConfirmDialog(
                    null,
                    "Do you really want to delete this appointment?",
                    "Delete" ,
                    JOptionPane.YES_NO_OPTION);
                if (d == JOptionPane.YES_OPTION){
                    appointmentDataSource.delete(selectedRow);
                    this.refreshPage();
                    this.setVisible(true);
                    JOptionPane.showConfirmDialog(
                        null,
                        "Appointment deleted.",
                        "Delele",
                        JOptionPane.CLOSED_OPTION);
                } else{
                    this.setVisible(true);
                }

            } else {
                JOptionPane.showConfirmDialog(
                    null, "Please select a row.", "Warning", JOptionPane.CLOSED_OPTION);
            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(this, "Error!");
        }

    }//GEN-LAST:event_deleteAppointmentButtonActionPerformed

    private void editAppointmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editAppointmentButtonActionPerformed
        try{
            int selectedRow = appointmentsTable.getSelectedRow();
            if (selectedRow != -1) {
                EditAppointment edit = new EditAppointment(this, appointmentDataSource, this.getSelectedIndex());
                edit.setDataFields();
                edit.setVisible(true);
                this.dispose();
            } else
                JOptionPane.showConfirmDialog(
                    null, "Please select a row.", "Warning", JOptionPane.CLOSED_OPTION);
        }catch(HeadlessException e) {
            JOptionPane.showMessageDialog(this, "Error!");
        }    
    }//GEN-LAST:event_editAppointmentButtonActionPerformed

    private void jTableTreatmentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTreatmentsMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount()==2){
            int row = jTableTreatments.getSelectedRow();
            if(row !=-1){
                editSelectedTreatment(row);
            }
        }
    }//GEN-LAST:event_jTableTreatmentsMouseClicked

    private void delTreatmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delTreatmentButtonActionPerformed
        // TODO add your handling code here:
        int row = jTableTreatments.getSelectedRow();
        if(row != -1){
            int response = JOptionPane.showConfirmDialog(rootPane, "Are you sure you want to delete this treatment?", 
                    "Delete Treatment", JOptionPane.YES_NO_CANCEL_OPTION);
            if(response == JOptionPane.YES_OPTION){
                treatTableModel.deleteTreatment(row);
            }
        }
    }//GEN-LAST:event_delTreatmentButtonActionPerformed

    private void editTreatmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editTreatmentButtonActionPerformed
        // TODO add your handling code here:
        int row = jTableTreatments.getSelectedRow();
        if(row !=-1){
            editSelectedTreatment(row);
        }
    }//GEN-LAST:event_editTreatmentButtonActionPerformed

    private void addTreatmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTreatmentButtonActionPerformed
        // TODO add your handling code here:
        
        EditTreatment dialog = new EditTreatment(this, true, null, true);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        if(dialog.isConfirmed()){
            Treatment updatedTreatment = dialog.getTreatment();
            treatTableModel.addTreatment(updatedTreatment);
        } 
    }//GEN-LAST:event_addTreatmentButtonActionPerformed


    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TabBarsPage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addTreatmentButton;
    private javax.swing.JPanel appointmentMain;
    private javax.swing.JTextField appointmentSearch;
    private javax.swing.JTable appointmentsTable;
    private javax.swing.JButton delTreatmentButton;
    private javax.swing.JButton deleteAppointmentButton;
    private javax.swing.JButton editAppointmentButton;
    private javax.swing.JButton editTreatmentButton;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollBar jScrollBar2;
    private javax.swing.JScrollBar jScrollBar3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTableTreatments;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JButton newAppointmnetButton;
    private javax.swing.JTextArea upcomingAptTextArea;
    // End of variables declaration//GEN-END:variables
}
